### ISSUE TITLE
Field `autoFormatFs` is never read

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/hdfs-operator#399]
### Affected version

0.0.0-dev

### Current and expected behavior

The field `spec.clusterConfig.autoFormatFs` is never read.

We could either:
1. Remove the field, as we have some smart mechanism that only formats NNs when needed.
2. We should read this field and do $stuff with it. In this case an HDFS expert needs to refine what $stuff is.

Relevant links:
Where the var is defined:
https://github.com/stackabletech/hdfs-operator/blob/664efadcca8a222757edf9dff3044fae6ace6a22/rust/crd/src/lib.rs#L94
The code flow which checks if a NN should be formated:
https://github.com/stackabletech/hdfs-operator/blob/664efadcca8a222757edf9dff3044fae6ace6a22/rust/operator/src/container.rs#L463-L502

### Would you like to work on fixing this bug?

None

**Comment by Jimvin** [comment]
Auto format as the default behaviour makes sense when the HDFS directories/volumes are empty and I can't see a scenario when you would want to disable this feature. More times than not this will trigger when the service is first deployed and at no other times. I'd be for removing this configuration property rather than implementing an auto format toggle switch.

**Comment by sbernauer** [comment]
If everyone agrees I can volunteer to delete the attribute :) Only bad thing: It's technically a breaking change...

**Comment by lfrancke** [comment]
Not right now. You can put it on the epic board but we have more important things to do right now.

**Comment by sbernauer** [comment]
Works for me, I was excepting this answer :) Hence I did volunteer and didn't directly do it :)
